name: ggs
channels:
  - conda-forge
dependencies:
  - python=3.9.16
  - pip=23.0.1
  - cudatoolkit=11.3.1
  - pip:
    - pandas==1.5.2
    - numpy==1.24.4
    - scikit-learn==1.2.0
    - scipy==1.8.1
    - matplotlib==3.9.0
    - tqdm==4.65.0
    - biotite==0.37.0
    - hydra-core==1.3.2
    - python-levenshtein==0.25.1
    - torch==1.12.0
    - pytorch-lightning==2.0.2
    - pyrootutils==1.0.4
    - hydra-colorlog==1.2.0
    - rich==13.3.5
    - wandb==0.15.3 
    - pykeops==2.1.2

